server:
#  ip: 47.107.252.131
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gyh?serverTimezone=GMT%2b8
#    url: jdbc:mysql://47.107.252.131:3306/gyh?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      multipart:
        max-file-size: 100MB #单个文件大小
        max-request-size: 500MB # 总文件大小（允许存储文件的文件夹大小）
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/learning/毕设/workspace/毕设/files/
#    path: /home/files/
